version: '3.2'
services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_DATABASE=dl
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_volume:/var/lib/mysql
      #  - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  ipfs:
    image: ipfs/kubo:v0.14.0
    ports:
      - '5001:5001'
      - "8081:8080"
      - "4001:4001"
    volumes:
      - ./data/ipfs:/data/ipfs
  nginx:
    container_name: mynginx
    image: nginx:latest
    ports:
        - '80:80'
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
#        - ./conf.d:/etc/nginx/conf.d
#        - ./logs:/var/log/nginx
    restart: always
