
INSERT INTO team ( team_name, team_profile, administrator, authority)
VALUES ("Dapp-Learning DAO co-founders", "Initial founding members and those who contributed significantly， Taking charge of  community vault.", "0x1F7b953113f4dFcBF56a1688529CC812865840e1", 10),
("Dapp-Learning DAO  builders", "Those who are willing to participate in the community and make outstanding contributions to community building", "", 9),
("Dapp-Learning DAO PR reviewers", "Responsible for review  PR of our repository", "", 8),
("Dapp-Learning DAO sharing group", "sharing in Dapp-Learning and earn reward", "", 7),
("Dapp-Learning DAO translation group", "Translate blockchain-related documents ", "", 6);
