INSERT INTO member (address, email, nickName, role,githubId)
VALUES
("0x1F7b953113f4dFcBF56a1688529CC812865840e1", "yanyanho126@gmail.com", "Yan", 0, "yanyanho");


INSERT INTO team ( team_name, team_profile, administrator, authority)
VALUES
("Dapp-Learning DAO co-founders", "Initial founding members and those who contributed significantly， Taking charge of  community vault.", "0x1F7b953113f4dFcBF56a1688529CC812865840e1", 0),
("Dapp-Learning DAO  builders", "Those who are willing to participate in the community and make outstanding contributions to community building", "0x1F7b953113f4dFcBF56a1688529CC812865840e1", 1),
("Dapp-Learning DAO PR reviewers", "Responsible for review  PR of our repository", "0x1F7b953113f4dFcBF56a1688529CC812865840e1", 2),
("Dapp-Learning DAO sharing group", "sharing in Dapp-Learning and earn reward", "0x1F7b953113f4dFcBF56a1688529CC812865840e1", 3),
("Dapp-Learning DAO translation group", "Translate blockchain-related documents ", "0x1F7b953113f4dFcBF56a1688529CC812865840e1", 4);


INSERT INTO sponsor(company, link, icon)
VALUES
("ETHEREUM FOUNDATION", "https://jobs.lever.co/ethereumfoundation","https://lever-client-logos.s3.us-west-2.amazonaws.com/b4cfe414-b949-4989-b62f-e34bb1817ee3-1644535907857.png"),
("ARBITRUM"," https://jobs.arbitrum.io/jobs", "https://cdn-customers.getro.com/arbitrum/images/cropped-Arbitrum_Horizontal-Logo-Full-color-White-background-scaled-1.jpg"),
("OPTIMISM", " https://jobs.optimism.io/jobs","https://assets-global.website-files.com/611dbb3c82ba72fbc285d4e2/611fd32ef63b79b5f8568d58_OPTIMISM-logo.svg"),
("SCROLL :", "https://jobs.lever.co/ScrollFoundation","https://lever-client-logos.s3.us-west-2.amazonaws.com/454cd96a-a8ab-4017-98d0-08f0356a498a-1692892834431.png");