server:
  port: 8080
  tomcat:
    max-swallow-size: 10MB
  servlet:
    session:
      timeout: 60m
      cookie:
        max-age: 3600
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/dl?allowPublicKeyRetrieval=true&useSSL=false
    #type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}
    maximum-pool-size: 20

  jpa:
    hibernate:
     ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  mail:
    host: ${SMTP_SERVER:smtp.gmail.com}
    port: ${SMTP_SERVER_PORT:587}
    username: ${MAIL_ADDRESS}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      cleanup-cron: 0 */3 * * * *
    timeout: 7200

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework.security: debug

web3j:
  client-address: "https://polygon-rpc.com"

oauth:
  registrations:
    github:
      clientId: "${GITHUB_CLIENT_ID}"
      clientSecret: "${GITHUB_CLIENT_SECRET}"
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      userInfoUri: https://api.github.com/user
    twitter:
      clientId:  "${TWITTER_CLIENT_KEY}"
      clientSecret:  "${TWITTER_CLIENT_SECRET}"
      callbackUrl: "${TWITTER_CALLBACK_URL}"

qcloud:
  #初始化用户身份信息 前往控制台密钥管理查看
  secretId: ${SECRET_ID}
  secretKey: ${SECRET_KEY}
  # 指定要上传到的存储桶
  bucketName: ${BUCKET_NAME}
  # 地区选择
  regionName: ${REGION_NAME}

login:
  filter: {LOGIN_FILTER:true}
