server:
  port: 8080
  servlet:
    session:
      timeout: 5m
      cookie:
        max-age: -1
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: "a9cbf17f96bd3a0d4d52"
            clientSecret: "bd2bdbd2383856cfbd445d560a5fba0abbb41944"

  datasource:
    #url: jdbc:mysql://81.69.8.95:3306/dl?useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/dl?allowPublicKeyRetrieval=true&useSSL=false
#type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 12345678
  jpa:
    hibernate:
     ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: yanyanho126@gmail.com
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      cleanup-cron: 0 */3 * * * *
    timeout:
      seconds:  900

logging:
  level:
    org.springframework.security: debug

oauth:
  registrations:
    github:
      auth-url: "/user/auth/github"
      client:
        clientId: 074acb9ef12af8ac37b1
        clientSecret: f0477511fdf1e8f6b63dd6ec913b1d2b9165747c
        accessTokenUri: https://github.com/login/oauth/access_token
        userAuthorizationUri: https://github.com/login/oauth/authorize
        clientAuthenticationScheme: form
      resource:
        userInfoUri: https://api.github.com/user

