server:
  port: 8080
  servlet:
    session:
      timeout: 5m
      cookie:
        max-age: -1
spring:
  datasource:
    #url: jdbc:mysql://81.69.8.95:3306/dl?useSSL=false
    url: jdbc:mysql://127.0.0.1:3306/dl?allowPublicKeyRetrieval=true&useSSL=false
#type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 12345678
  jpa:
    hibernate:
     ddl-auto: create
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: yanyanho126@gmail.com
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      cleanup-cron: 0 */3 * * * *
    timeout:
      seconds:  900

logging:
  level:
    org.springframework.security: debug

oauth:
  registrations:
    github:
      clientId: "Iv1.74aecf988af67044"
      clientSecret: "d0f38f58e98bb3dbb9a6bf6a2e1211a4feb24767"
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      userInfoUri: https://api.github.com/user


