server:
  port: 8080
  servlet:
    session:
      timeout: 60m
      cookie:
        max-age: -1
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dl?allowPublicKeyRetrieval=true&useSSL=false
    #type: com.alibaba.druid.pool.DruidDataSource
    username: root
    #    password: 12345678
    password: {{SPRING_DATASOURCE_PASSWORD}}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  mail:
    host: smtp.163.com
    port: 465
    username: 15503679582@163.com
    password: OXWEDGWEOGIGVWJN
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      cleanup-cron: 0 */3 * * * *
    timeout: 7200
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.springframework.security: debug

ipfs:
  url: ""

web3j:
  client-address: "https://polygon-rpc.com"

oauth:
  registrations:
    github:
      clientId: "Iv1.74aecf988af67044"
      clientSecret: "d0f38f58e98bb3dbb9a6bf6a2e1211a4feb24767"
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      userInfoUri: https://api.github.com/user

qcloud:
  secretId: {{SECRET_ID}}
  secretKey: {{SECRET_KEY}}
  bucketName: {{BUCKET_NAME}}
  regionName: {{REGION_NAME}}

login:
  filter: true