server:
  servlet:
    session:
      timeout: 5m
      cookie:
        max-age: -1
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dl?useSSL=false
#type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
     ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: yanyanho126@gmail.com
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      cleanup-cron: 0 */3 * * * *
    timeout:
      seconds:  900

