version: '3.5'
services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_DATABASE=dl
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - network
    volumes:
      - ./mysql_volume:/var/lib/mysql
      #- ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  network:
    driver: bridge
    name: dl-dependency-network