version: '3.2'
services:
  dl:
    container_name: dl-backend
    image: yuanmomo/dl-official-website-backend:dev-latest
    environment:
      # change the profile name and password according to your env.
      - spring_profiles_active=dev
      - SPRING_DATASOURCE_PASSWORD=
      - BUCKET_NAME=
      - REGION_NAME=
      - SECRET_ID=
      - SECRET_KEY=
      - GITHUB_CLIENT_ID=
      - GITHUB_CLIENT_SECRET=
      - MAIL_ADDRESS=
      - MAIL_PASSWORD=
    ports:
      - '8080:8080'
    volumes:
      - ./logs:/logs
    restart: always
    networks:
      - dl-dependency-network

networks:
  dl-dependency-network:
    external: true