version: '3.5'
services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_DATABASE=dl
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - network
    volumes:
      - ./mysql_volume:/var/lib/mysql
      #- ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    networks:
      - network
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx

networks:
  network:
    driver: bridge
    name: dl-dependency-network