version: '3.5'
services:

  dl-backend:
    container_name: dl-backend
    image: yuanmomo/dl-official-website-backend:dev-latest
    environment:
      # change the profile name and password according to your env.
      - spring_profiles_active=dev
      # MySQL password
      - SPRING_DATASOURCE_PASSWORD=
      # QCloud
      - BUCKET_NAME=
      - REGION_NAME=
      - SECRET_ID=
      - SECRET_KEY=
      # GMAIL
      - MAIL_ADDRESS=
      - MAIL_PASSWORD=
      # Chain ids
      - CHAIN_IDS=
      # CRON
      - CRON_REDPACKET=
      - CRON_DIS=
    ports:
      - '8080:8080'
      - '127.0.0.1:9093:9093'
    volumes:
      - ./logs:/logs
    restart: always
    networks:
      - dl-backend


networks:
  dl-backend:
    name: dl-dependency-network
    external: true