name: Deploy Official-website-backend to dev/prod Server

on:
  push:
    branches:
      - dev
    tags:
      - 'v*.*.*'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: dl-backend-env

    env:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_IMAGE_VERSION: dev-latest
      DOCKER_IMAGE_NAME: dl-official-website-backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables based on branch or tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "DOCKER_IMAGE_VERSION=dev-latest" >> $GITHUB_ENV
            echo "BRANCH_OR_TAG_NAME=dev" >> $GITHUB_ENV
          else
            echo "Build production release for tag ${{ github.ref }}"
            echo "DOCKER_IMAGE_VERSION=${{ github.ref }}" >> $GITHUB_ENV
            echo "BRANCH_OR_TAG_NAME=${{ github.ref }}" >> $GITHUB_ENV
          fi

      - name: Display current branch
        run: |
          echo "Current build is on $BRANCH_OR_TAG_NAME"

      - name: Build Docker image
        run: |
          docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION .
          if [[ $DOCKER_IMAGE_VERSION =~ "v[0-9]+.[0-9]+.[0-9]+" ]]; then
            docker tag $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:prod-latest
          fi

      - name: Push Docker image to registry
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION
          docker push $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:prod-latest

      - name: SSH login to server and restart service on DEV server
        uses: appleboy/ssh-action@master
        if: contains(github.ref, 'dev')
        with:
          host: ${{ vars.DEV_SERVER_HOST }}
          username: ${{ vars.DEV_SERVER_USERNAME }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          port: ${{ vars.DEV_PORT }}
          script: |
            cd /root/Official-website-backend
            docker compose pull 
            docker-compose down && docker-compose up -d

      - name: SSH login to server and restart service on PROD server
        uses: appleboy/ssh-action@master
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          host: ${{ vars.PROD_SERVER_HOST }}
          username: ${{ vars.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
          port: ${{ vars.PROD_PORT }}
          script: |
            cd /data/Official-website-backend
            docker pull $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_VERSION
            docker pull $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:prod-latest
            echo "Exec docker-compose down && docker-compose up -d in $(PWD)" > deploy.txt
#            docker-compose down && docker-compose up -d
